version: '3.8'

services:
  app:
    build: .
    container_name: cakephp_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: cakephp_db
    environment:
      MYSQL_DATABASE: a2i_demo_db
      MYSQL_USER: a2i_user
      MYSQL_PASSWORD: StrongPassword123
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"

