name: Deploy to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on Oracle VM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Oracle VM via SSH
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd /var/www/html/a2i-demo-project
          git pull origin main
          sudo docker compose down
          sudo docker compose up --build -d
